name: 'PR Auto Changelog'
description: 'Automatically update changelog based on PR comments and conventional commits'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  changelog-path:
    description: 'Path to the changelog file'
    required: false
    default: 'CHANGELOG.md'
  auto-categorize:
    description: 'Auto-categorize based on conventional commit format'
    required: false
    default: 'true'
  comment-trigger:
    description: 'Comment trigger phrase'
    required: false
    default: '/changelog:'
outputs:
  changelog-updated:
    description: 'Whether the changelog was updated'
  changes-added:
    description: 'Number of changes added to changelog'
runs:
  using: 'node20'
  main: 'dist/index.js'
