name: "PR Auto Changelog Integration Test"

on:
  pull_request:
    types: [opened, synchronize, edited]
  issue_comment:
    types: [created, edited]

jobs:
  test-changelog:
    runs-on: ubuntu-latest
    # Only run on PRs and comments on PRs
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    permissions:
      contents: write
      pull-requests: read
      issues: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Run PR Auto Changelog
        id: changelog
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-path: 'CHANGELOG.md'
          auto-categorize: true
          comment-trigger: '/changelog:'
        
      - name: Display Results
        run: |
          echo "## 🔍 Test Results"
          echo "- **Changelog Updated:** ${{ steps.changelog.outputs.changelog-updated }}"
          echo "- **Changes Added:** ${{ steps.changelog.outputs.changes-added }}"
          echo "- **Event Type:** ${{ github.event_name }}"
          echo "- **Event Action:** ${{ github.event.action }}"
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "- **PR Title:** ${{ github.event.pull_request.title }}"
            echo "- **PR Number:** #${{ github.event.pull_request.number }}"
            echo "- **Branch:** ${{ github.event.pull_request.head.ref }}"
          elif [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "- **Comment:** ${{ github.event.comment.body }}"
            echo "- **PR Number:** #${{ github.event.issue.number }}"
            echo "- **Comment Action:** ${{ github.event.action }}"
          fi
          
      - name: Show Updated Changelog
        if: steps.changelog.outputs.changelog-updated == 'true'
        run: |
          echo "## 📝 Updated Changelog (Last 20 lines):"
          echo '```markdown'
          tail -20 CHANGELOG.md
          echo '```'
          
      - name: Verify Git Changes
        if: steps.changelog.outputs.changelog-updated == 'true'
        run: |
          echo "## 📋 Git Status After Update:"
          git status --porcelain
          echo ""
          echo "## 📊 Git Log (Last Commit):"
          git log -1 --oneline
          echo ""
          echo "## 🌿 Current Branch:"
          git branch --show-current 