name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      issues: read
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Test PR Auto Changelog Action
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        changelog-path: 'test-changelog.md'
        auto-categorize: true
        comment-trigger: '/changelog:'
      env:
        # Mock PR event for testing
        GITHUB_EVENT_NAME: 'pull_request'
        GITHUB_REPOSITORY: ${{ github.repository }}
    - name: Verify test completed
      run: |
        echo "✅ PR Auto Changelog action test completed successfully"
        if [ -f "test-changelog.md" ]; then
          echo "📝 Test changelog file was created"
          cat test-changelog.md
        else
          echo "ℹ️  No changelog file created (expected for non-PR events)"
        fi
