name: "Comprehensive CI"

on:
  push:
    branches: [ main, 'releases/*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm test
        
      - name: Lint code
        run: npm run lint
        
      - name: Build distribution
        run: npm run prepare
        
      - name: Verify dist is up to date
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "❌ Distribution files are out of date. Run 'npm run prepare' and commit the changes."
            git diff dist/
            exit 1
          else
            echo "✅ Distribution files are up to date."
          fi

  # Basic smoke test - verify action loads without errors
  smoke-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Test action loads
        uses: ./
        with:
          github-token: 'fake-token-for-testing'
          changelog-path: 'non-existent.md'
        continue-on-error: true # Expected to fail gracefully